const SVG_NS='http://www.w3.org/2000/svg';
export function mount({container,definition,api,close}){
  container.innerHTML=`
    <header class="game-header-new"><div><p class="game-kicker-new mono">АБСТРАКЦИЯ</p><h2>${definition.title}</h2><p data-instruction>Выберите фигуру, которая совпадает с образцом после поворота.</p></div><div class="game-progress-new" data-progress>1. Инструкция</div></header>
    <main class="game-stage-new gm17-module is-instruction-stage" data-stage>
      <section class="gm17-intro" data-intro><h3>Как выполнять задание</h3><ol><li>Рассмотрите фигуру-образец.</li><li>Представьте, как она выглядит после поворота.</li><li>Выберите ту же фигуру в другом положении; другая или зеркальная форма не подходит.</li></ol><p class="gm17-example-title">Посмотрите пример</p><div class="gm17-media-placeholder"><span aria-hidden="true">▶</span><strong>Здесь будет GIF с примером</strong><small>Визуальная инструкция будет добавлена позже</small></div><button type="button" class="icon-btn primary-btn" data-start-training><span>Перейти к тренировке</span></button></section>
      <section class="gm17-training" data-training hidden><h3>Тренировочный пример</h3><p>Выберите фигуру, совпадающую с образцом после поворота.</p><div class="gm17-module-play"><section class="gm17-module-section"><p class="mono">ОБРАЗЕЦ</p><div class="gm17-module-sample" data-training-sample></div></section><div class="gm17-module-divider"></div><section class="gm17-module-section"><p class="mono">ВЫБЕРИТЕ ФИГУРУ</p><div class="gm17-module-choices" data-training-choices></div></section></div><p data-training-feedback></p></section>
      <section class="game-intro-new gm17-training-complete" data-training-complete hidden><h3>Обучение завершено</h3><p>Вы правильно нашли повёрнутую фигуру.</p><div class="gm17-training-actions"><button type="button" class="icon-btn gm17-training-repeat" data-repeat-training><span>Повторить тренировку</span></button><button type="button" class="icon-btn primary-btn" data-confirm-start><span>Начать игру</span></button></div></section>
      <section class="gm17-game" data-game hidden><div class="gm17-module-play" data-play><section class="gm17-module-section"><p class="mono">ОБРАЗЕЦ</p><div class="gm17-module-sample" data-sample></div></section><div class="gm17-module-divider"></div><section class="gm17-module-section"><p class="mono">ВЫБЕРИТЕ СОВПАДАЮЩУЮ ФИГУРУ</p><div class="gm17-module-choices" data-choices></div></section></div><div class="game-result-new" data-result hidden><h3>Игра завершена</h3><p data-result-text></p><button type="button" class="icon-btn primary-btn" data-restart><span>Ещё раз</span></button></div></section>
    </main><footer class="game-actions-new"><button type="button" class="icon-btn" data-close><span>К выбору игр</span></button></footer>`;
  const stage=container.querySelector('[data-stage]'),instruction=container.querySelector('[data-instruction]'),progress=container.querySelector('[data-progress]');
  const intro=container.querySelector('[data-intro]'),training=container.querySelector('[data-training]'),trainingSample=container.querySelector('[data-training-sample]'),trainingChoices=container.querySelector('[data-training-choices]'),trainingFeedback=container.querySelector('[data-training-feedback]'),trainingComplete=container.querySelector('[data-training-complete]');
  const game=container.querySelector('[data-game]'),play=container.querySelector('[data-play]'),sample=container.querySelector('[data-sample]'),choices=container.querySelector('[data-choices]'),result=container.querySelector('[data-result]'),resultText=container.querySelector('[data-result-text]'),restart=container.querySelector('[data-restart]');
  let state=null,accepting=false,shownAt=0,token=0,active=true;const timers=new Set();const delay=milliseconds=>new Promise(resolve=>{const id=setTimeout(()=>{timers.delete(id);resolve()},milliseconds);timers.add(id)});const showOnly=target=>[intro,training,trainingComplete,game].forEach(section=>{section.hidden=section!==target});
  function createShape(shape){if(shape.image){const image=document.createElement('img');image.className='gm17-image-silhouette';image.src=`/game-assets/objects/${shape.image}`;image.alt='';image.style.transform=`rotate(${Number(shape.rotation)||0}deg)`;return image}const svg=document.createElementNS(SVG_NS,'svg');svg.setAttribute('viewBox','0 0 100 100');const group=document.createElementNS(SVG_NS,'g');group.setAttribute('transform',`rotate(${Number(shape.rotation)||0} 50 50)`);const polygon=document.createElementNS(SVG_NS,'polygon');polygon.setAttribute('points',(shape.points||[]).map(point=>point.join(',')).join(' '));group.append(polygon);svg.append(group);return svg}
  function choiceButton(shape,handler){const button=document.createElement('button');button.type='button';button.className='gm17-module-choice';button.append(createShape(shape));button.onclick=()=>handler(shape,button);return button}
  const step=[[18,18],[58,18],[58,38],[82,38],[82,82],[42,82],[42,62],[18,62]],flag=[[18,12],[78,12],[60,35],[78,58],[34,58],[34,88],[18,88]];
  const pentT=[[16,16],[39,16],[61,16],[84,16],[84,39],[61,39],[61,61],[61,84],[39,84],[39,61],[39,39],[16,39]],pentF=[[39,16],[61,16],[84,16],[84,39],[61,39],[61,61],[61,84],[39,84],[39,61],[16,61],[16,39],[39,39]];
  const longBranch=[[16,24],[33,24],[50,24],[67,24],[84,24],[84,42],[67,42],[50,42],[50,58],[50,76],[33,76],[33,58],[33,42],[16,42]],cornerTail=[[24,16],[42,16],[42,33],[42,50],[58,50],[76,50],[76,67],[76,84],[58,84],[58,67],[42,67],[24,67],[24,50],[24,33]];
  const trainingShapeSets={'геометрические фигуры':{sample:{points:step},wrong:{points:flag}},'силуэты предметов':{sample:{image:'key.png'},wrong:{image:'umbrella.png'}},'силуэты животных':{sample:{image:'cat.png'},wrong:{image:'rabbit.png'}}};
  const trainingShapes=trainingShapeSets[String(definition.selected_stimulus_set||'').toLowerCase()]||trainingShapeSets['геометрические фигуры'];
  function beginTraining(){token+=1;stage.classList.remove('is-instruction-stage');showOnly(training);progress.textContent='2. Тренировка';instruction.textContent='Найдите ту же фигуру после поворота.';trainingFeedback.textContent='';trainingFeedback.className='';trainingSample.replaceChildren(createShape({...trainingShapes.sample,rotation:0}));const variants=[{id:'wrong',...trainingShapes.wrong,rotation:90},{id:'correct',...trainingShapes.sample,rotation:90}];trainingChoices.replaceChildren(...variants.map(shape=>choiceButton(shape,(selected,button)=>{if(button.disabled)return;if(selected.id!=='correct'){button.classList.add('is-wrong');button.disabled=true;trainingFeedback.textContent='Это другая форма. Попробуйте ещё раз.';trainingFeedback.className='is-wrong';return}[...trainingChoices.children].forEach(item=>item.disabled=true);button.classList.add('is-correct');trainingFeedback.textContent='Верно.';trainingFeedback.className='is-correct';const currentToken=token;setTimeout(()=>{if(!active||currentToken!==token)return;showOnly(trainingComplete);progress.textContent='Обучение завершено';instruction.textContent='Тренировочный пример выполнен правильно.'},450)})))}

  function renderTrial(payload){state=payload;accepting=true;shownAt=performance.now();sample.replaceChildren(createShape(payload.sample));choices.replaceChildren(...payload.choices.map(choice=>choiceButton(choice,(selected,button)=>submitAnswer(selected.id,button))));progress.textContent=`Проба ${payload.trial} из ${payload.trial_count}`;instruction.textContent='Выберите фигуру, которая совпадает с образцом после поворота.';result.hidden=true;play.hidden=false}
  async function submitAnswer(selectedId,button){if(!accepting||!state)return;accepting=false;const currentToken=token;button.classList.add('is-selected');choices.querySelectorAll('button').forEach(item=>{item.disabled=true});if(!active||currentToken!==token)return;try{const payload=await api.answer({session_id:state.session_id,selected_id:selectedId,timestamp_ms:Date.now()});if(!payload.finished){renderTrial(payload);return}play.hidden=true;result.hidden=false;restart.disabled=false;progress.textContent='Завершено';instruction.textContent='Все пробы завершены.';resultText.textContent=`Правильных ответов: ${Math.round(Number(payload.metrics?.u01_correct_action_rate||0)*100)}%.`}catch(error){button.classList.remove('is-selected');choices.querySelectorAll('button').forEach(item=>{item.disabled=false});accepting=true;instruction.textContent=`Не удалось сохранить ответ: ${error.message}`}}
  async function begin(){token+=1;accepting=false;restart.disabled=true;showOnly(game);play.hidden=true;result.hidden=true;instruction.textContent='Подготавливаю задание…';try{renderTrial(await api.start())}catch(error){instruction.textContent=`Не удалось начать игру: ${error.message}`;restart.disabled=false}}

  container.querySelector('[data-start-training]').onclick=beginTraining;container.querySelector('[data-repeat-training]').onclick=beginTraining;container.querySelector('[data-confirm-start]').onclick=begin;restart.onclick=begin;container.querySelector('[data-close]').onclick=()=>{active=false;accepting=false;token+=1;timers.forEach(id=>clearTimeout(id));timers.clear();close()};
  const style=document.createElement('style');style.textContent=`
    .gm17-module{display:grid;place-items:center;text-align:center;overflow:hidden}.gm17-module.is-instruction-stage{align-items:start;padding-top:clamp(14px,2.4vh,30px)}.gm17-intro,.gm17-training,.gm17-game{width:min(980px,100%)}.gm17-intro h3,.gm17-training h3{margin:0 0 10px;font-size:clamp(19px,2.3vw,25px)}.gm17-intro ol{width:min(700px,100%);margin:0 auto 16px;padding-left:28px;color:#52606d;text-align:left;font-size:clamp(14px,1.6vw,18px);line-height:1.4}.gm17-intro li+li{margin-top:5px}.gm17-example-title{margin:0 0 7px;font-weight:700}.gm17-media-placeholder{box-sizing:border-box;display:flex;width:min(620px,100%);height:clamp(130px,22vh,230px);margin:0 auto 18px;flex-direction:column;align-items:center;justify-content:center;gap:7px;border:2px dashed #b8cbd5;border-radius:16px;background:#eaf1f4;color:#52606d}.gm17-media-placeholder>span{display:grid;width:46px;height:46px;place-items:center;border-radius:50%;background:#d3e2e9;color:#168ba8}.gm17-media-placeholder strong{color:#263744}.gm17-training>p{color:#52606d}
    .gm17-module-play{width:min(980px,100%);display:grid;grid-template-columns:minmax(180px,1fr) 1px minmax(380px,2fr);align-items:center;gap:clamp(20px,4vw,56px)}.gm17-module-play[hidden]{display:none}.gm17-module-section>p{margin:0 0 16px;color:#667784;font-size:12px;letter-spacing:.14em}.gm17-module-sample,.gm17-module-choice{border:2px solid #d1dde3;border-radius:20px;background:#fff}.gm17-module-sample{width:min(250px,29vh,100%);aspect-ratio:1;margin:auto;padding:clamp(20px,3vh,30px)}.gm17-module-divider{align-self:stretch;background:#d8e0e5}.gm17-module-choices{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:clamp(14px,2vw,26px)}.gm17-module-choice{aspect-ratio:1;padding:clamp(18px,3vh,30px);color:#17212b}.gm17-module-choice:hover:not(:disabled){border-color:#36b7d7}.gm17-module-choice.is-selected{border-color:#168ba8;background:#e8f8fc}.gm17-module-choice.is-correct{border-color:#16875c;background:#dff5e9}.gm17-module-choice.is-wrong{border-color:#c63d4b;background:#fde5e8}.gm17-module-sample svg,.gm17-module-choice svg,.gm17-image-silhouette{width:100%;height:100%;display:block}.gm17-module-sample polygon,.gm17-module-choice polygon{fill:#17212b}.gm17-image-silhouette{object-fit:contain;filter:brightness(0) saturate(100%);transform-origin:center}.gm17-training>[data-training-feedback].is-correct{color:#167950}.gm17-training>[data-training-feedback].is-wrong{color:#b33443}
    .gm17-training-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.gm17-training-repeat{border-color:#60727d;background:#fff;color:#17212b}.gm17-training-repeat span{color:#17212b}.gm17-intro[hidden],.gm17-training[hidden],.gm17-training-complete[hidden],.gm17-game[hidden]{display:none}@media(max-height:700px){.gm17-module.is-instruction-stage{padding-top:8px}.gm17-intro ol{margin-bottom:7px;font-size:13px;line-height:1.25}.gm17-media-placeholder{height:clamp(100px,18vh,140px);margin-bottom:8px}.gm17-module-sample{width:min(205px,27vh);padding:18px}.gm17-module-choice{padding:16px}}@media(max-width:680px){.gm17-module-play{grid-template-columns:1fr 1.5fr;gap:14px}.gm17-module-divider{display:none}.gm17-module-choices{gap:8px}}
  `;container.append(style);return()=>{active=false;accepting=false;token+=1;timers.forEach(id=>clearTimeout(id));timers.clear()}
}
