export function mount({ container, definition, api, close }) {
  const tutorialTargets = {
    "буква Т": { symbol: "Т", description: "красная буква «Т»", findLabel: "красную букву «Т»", group: "букв" },
    "треугольник": { symbol: "▲", description: "красный треугольник", findLabel: "красный треугольник", group: "фигур" },
    "число 3": { symbol: "3", description: "красное число «3»", findLabel: "красное число «3»", group: "цифр" },
  };
  const tutorialTarget = tutorialTargets[definition.selected_stimulus_set] || tutorialTargets["буква Т"];
  container.innerHTML = `
    <header class="game-header-new"><div><p class="game-kicker-new mono">ВНИМАНИЕ</p><h2>${definition.title}</h2><p data-instruction>Запомните цель и найдите её среди похожих фигур.</p></div><div class="game-progress-new" data-progress>1. Инструкция</div></header>
    <main class="game-stage-new gm07-module is-instruction-stage" data-stage>
      <section class="gm07-intro" data-intro><h3>Как выполнять задание</h3><ol><li>Цель — ${tutorialTarget.description} без поворота.</li><li>Найдите её среди красных, чёрных и повёрнутых ${tutorialTarget.group}.</li><li>Если точного совпадения нет, нажмите «Цели нет».</li></ol><p class="gm07-example-title">Посмотрите пример</p><div class="gm07-media-placeholder"><span aria-hidden="true">▶</span><strong>Здесь будет GIF с примером</strong><small>Визуальная инструкция будет добавлена позже</small></div><button type="button" class="icon-btn primary-btn" data-start-training><span>Перейти к тренировке</span></button></section>
      <section class="gm07-training" data-training hidden><h3>Тренировочный пример</h3><p>Найдите ${tutorialTarget.findLabel} без поворота.</p><div class="gm07-target-row"><span>Образец:</span><div class="gm07-module-target">${tutorialTarget.symbol}</div></div><div class="gm07-module-grid gm07-training-grid" data-training-grid></div><p data-training-feedback aria-live="polite"></p></section>
      <section class="game-intro-new gm07-training-complete" data-training-complete hidden><h3>Обучение завершено</h3><p>Вы правильно нашли цель.</p><div class="gm07-training-actions"><button type="button" class="icon-btn gm07-training-repeat" data-repeat-training><span>Повторить тренировку</span></button><button type="button" class="icon-btn primary-btn" data-confirm-start><span>Начать игру</span></button></div></section>
      <section class="gm07-game" data-game hidden><div class="gm07-module-play" data-play><div class="gm07-module-grid" data-grid></div><button type="button" class="icon-btn gm07-module-absent" data-absent><span>Цели нет</span></button></div><div class="game-result-new" data-result hidden><h3>Игра завершена</h3><p data-result-text></p><button type="button" class="icon-btn primary-btn" data-restart><span>Ещё раз</span></button></div></section>
    </main><footer class="game-actions-new"><button type="button" class="icon-btn" data-close><span>К выбору игр</span></button></footer>`;

  const stage=container.querySelector('[data-stage]'),instruction=container.querySelector('[data-instruction]'),progress=container.querySelector('[data-progress]');
  const intro=container.querySelector('[data-intro]'),training=container.querySelector('[data-training]'),trainingGrid=container.querySelector('[data-training-grid]'),trainingFeedback=container.querySelector('[data-training-feedback]'),trainingComplete=container.querySelector('[data-training-complete]');
  const game=container.querySelector('[data-game]'),play=container.querySelector('[data-play]'),grid=container.querySelector('[data-grid]'),absent=container.querySelector('[data-absent]'),result=container.querySelector('[data-result]'),resultText=container.querySelector('[data-result-text]'),restart=container.querySelector('[data-restart]');
  let state=null,acceptingInput=false,renderToken=0,active=true;const timers=new Set();
  const delay=milliseconds=>new Promise(resolve=>{const id=setTimeout(()=>{timers.delete(id);resolve()},milliseconds);timers.add(id)});
  const showOnly=target=>[intro,training,trainingComplete,game].forEach(section=>{section.hidden=section!==target});
  function stimulusButton(stimulus,onClick){const button=document.createElement('button');button.type='button';button.className=`gm07-module-stimulus is-${stimulus.color}`;button.setAttribute('aria-label',`${stimulus.color==='red'?'Красная':'Чёрная'} цель ${stimulus.symbol}`);const symbol=document.createElement('span');symbol.textContent=stimulus.symbol;symbol.style.transform=`rotate(${Number(stimulus.rotation)||0}deg)`;button.append(symbol);button.onclick=()=>onClick(stimulus,button);return button}
  function renderStimuli(target,stimuli,onClick,columns=5){target.style.gridTemplateColumns=`repeat(${columns},1fr)`;target.replaceChildren(...stimuli.map(stimulus=>stimulusButton(stimulus,onClick)))}

  function beginTraining(){
    renderToken+=1;stage.classList.remove('is-instruction-stage');showOnly(training);progress.textContent='2. Тренировка';instruction.textContent='Найдите точное совпадение с образцом.';trainingFeedback.textContent='';trainingFeedback.className='';
    const symbol=tutorialTarget.symbol;
    const stimuli=[{id:'a',symbol,color:'black',rotation:0},{id:'b',symbol,color:'red',rotation:90},{id:'target',symbol,color:'red',rotation:0},{id:'d',symbol,color:'black',rotation:180},{id:'e',symbol,color:'red',rotation:270},{id:'f',symbol,color:'black',rotation:90}];
    renderStimuli(trainingGrid,stimuli,(stimulus,button)=>{if(button.disabled)return;if(stimulus.id!=='target'){button.classList.add('is-wrong');button.disabled=true;trainingFeedback.textContent='Это не точное совпадение. Попробуйте ещё раз.';trainingFeedback.className='is-wrong';setTimeout(()=>{if(!active)return;button.classList.remove('is-wrong');button.disabled=false},500);return}[...trainingGrid.children].forEach(item=>item.disabled=true);button.classList.add('is-correct');trainingFeedback.textContent='Верно.';trainingFeedback.className='is-correct';setTimeout(()=>{if(!active)return;showOnly(trainingComplete);progress.textContent='Обучение завершено';instruction.textContent='Тренировочный пример выполнен правильно.'},450)});
  }

  async function renderTrial(payload){const token=++renderToken;state=payload;acceptingInput=false;progress.textContent=`Проба ${payload.trial} из ${payload.trial_count}`;instruction.textContent='Приготовьтесь…';result.hidden=true;play.hidden=true;await delay(400);if(!active||token!==renderToken)return;renderStimuli(grid,payload.stimuli||[],stimulus=>answer(stimulus.id),payload.grid_size||5);grid.classList.toggle('is-dense',(payload.grid_size||5)>5);play.hidden=false;instruction.textContent='Нажмите на цель или выберите «Цели нет».';acceptingInput=true}
  async function begin(){renderToken+=1;acceptingInput=false;restart.disabled=true;showOnly(game);instruction.textContent='Подготавливаю задание…';try{await renderTrial(await api.start())}catch(error){instruction.textContent=`Не удалось начать игру: ${error.message}`;restart.disabled=false}}
  async function answer(selectedId){if(!acceptingInput||!state)return;acceptingInput=false;[...grid.children].forEach(item=>{item.disabled=true});absent.disabled=true;try{const payload=await api.answer({session_id:state.session_id,selected_id:selectedId,timestamp_ms:Date.now()});absent.disabled=false;if(!active)return;if(!payload.finished){await renderTrial(payload);return}play.hidden=true;result.hidden=false;restart.disabled=false;progress.textContent='Завершено';instruction.textContent='Все 10 проб завершены.';const accuracy=Math.round(Number(payload.metrics?.u01_correct_action_rate||0)*100);resultText.textContent=`Правильных ответов: ${accuracy}%.`}catch(error){instruction.textContent=`Не удалось сохранить ответ: ${error.message}`;[...grid.children].forEach(item=>{item.disabled=false});absent.disabled=false;acceptingInput=true}}

  absent.onclick=()=>answer(null);container.querySelector('[data-start-training]').onclick=beginTraining;container.querySelector('[data-repeat-training]').onclick=beginTraining;container.querySelector('[data-confirm-start]').onclick=begin;restart.onclick=begin;container.querySelector('[data-close]').onclick=()=>{active=false;renderToken+=1;timers.forEach(id=>clearTimeout(id));timers.clear();close()};
  const style=document.createElement('style');style.textContent=`
    .gm07-module{text-align:center}.gm07-module.is-instruction-stage{align-items:start;padding-top:clamp(14px,2.4vh,30px)}.gm07-intro,.gm07-training,.gm07-game{width:min(900px,100%)}.gm07-intro h3,.gm07-training h3{margin:0 0 10px;font-size:clamp(19px,2.3vw,25px)}.gm07-intro ol{width:min(700px,100%);margin:0 auto 16px;padding-left:28px;color:#52606d;text-align:left;font-size:clamp(14px,1.6vw,18px);line-height:1.4}.gm07-intro li+li{margin-top:5px}.gm07-example-title{margin:0 0 7px;font-weight:700}
    .gm07-media-placeholder{box-sizing:border-box;display:flex;width:min(620px,100%);height:clamp(130px,22vh,230px);margin:0 auto 18px;flex-direction:column;align-items:center;justify-content:center;gap:7px;border:2px dashed #b8cbd5;border-radius:16px;background:#eaf1f4;color:#52606d}.gm07-media-placeholder>span{display:grid;width:46px;height:46px;place-items:center;border-radius:50%;background:#d3e2e9;color:#168ba8}.gm07-media-placeholder strong{color:#263744}
    .gm07-training>p{margin:0 0 8px;color:#52606d}.gm07-target-row{display:flex;align-items:center;justify-content:center;gap:12px;margin-bottom:14px}.gm07-module-target{display:grid;place-items:center;width:70px;aspect-ratio:1;border:2px solid #d4dfe4;border-radius:16px;background:#fff;color:#d92f42;font-size:44px;font-weight:800}.gm07-module-play{width:min(900px,94%);margin:auto}.gm07-module-play[hidden]{display:none}.gm07-module-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:clamp(8px,1.5vw,16px);margin-bottom:clamp(14px,2vh,24px)}.gm07-module-grid.is-dense{gap:3px}.gm07-module-grid.is-dense .gm07-module-stimulus{border-radius:7px}.gm07-module-grid.is-dense .gm07-module-stimulus span{font-size:clamp(13px,3.5vh,30px)}.gm07-training-grid{grid-template-columns:repeat(3,1fr);width:min(620px,90%);margin-left:auto;margin-right:auto}.gm07-module-stimulus{display:grid;place-items:center;aspect-ratio:1;min-width:0;border:2px solid #cfdae0;border-radius:18px;background:#fff}.gm07-module-stimulus:hover:not(:disabled){border-color:#69b8c9}.gm07-module-stimulus span{display:block;font-size:clamp(38px,8vh,72px);font-weight:800;line-height:1;pointer-events:none}.gm07-module-stimulus.is-red{color:#d92f42}.gm07-module-stimulus.is-black{color:#17212b}.gm07-module-stimulus.is-correct{border:4px solid #1d9b69;background:#e4f7ef}.gm07-module-stimulus.is-wrong{border:4px solid #d64b59;background:#fdebed}.gm07-training>[data-training-feedback].is-correct{color:#167950}.gm07-training>[data-training-feedback].is-wrong{color:#b33443}
    .gm07-module-absent{min-width:180px;border-width:2px!important;border-color:#465b66!important;background:#fff!important;color:#17212b!important;font-weight:750;box-shadow:0 4px 12px rgba(23,33,43,.14)!important}.gm07-module-absent:hover:not(:disabled){border-color:#168ba8!important;background:#dff5fa!important}.gm07-training-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.gm07-training-repeat{border-color:#60727d;background:#fff;color:#17212b}.gm07-training-repeat span{color:#17212b}.gm07-intro[hidden],.gm07-training[hidden],.gm07-training-complete[hidden],.gm07-game[hidden]{display:none}@media(max-height:700px){.gm07-module.is-instruction-stage{padding-top:8px}.gm07-intro ol{margin-bottom:7px;font-size:13px;line-height:1.25}.gm07-media-placeholder{height:clamp(100px,18vh,140px);margin-bottom:8px}.gm07-module-stimulus span{font-size:clamp(26px,7vh,48px)}}
  `;container.append(style);return()=>{active=false;renderToken+=1;acceptingInput=false;timers.forEach(id=>clearTimeout(id));timers.clear()}
}
