export function mount({container,definition,api,close}){
  container.innerHTML=`
    <header class="game-header-new"><div><p class="game-kicker-new mono">ПАМЯТЬ</p><h2>${definition.title}</h2><p data-instruction>Послушайте и повторите последовательность кнопками в том же ритме.</p></div><div class="game-progress-new" data-progress>1. Инструкция</div></header>
    <main class="game-stage-new gm06-stage is-instruction-stage" data-stage>
      <section class="gm06-intro" data-intro><h3>Как выполнять задание</h3><ol><li>Три цветные кнопки по очереди загорятся и прозвучат.</li><li>Запомните порядок звуков и паузы между ними.</li><li>Повторите последовательность, нажимая те же кнопки.</li></ol><p class="gm06-example-title">Посмотрите пример</p><div class="gm06-media-placeholder"><span aria-hidden="true">▶</span><strong>Здесь будет GIF с примером</strong><small>Визуальная инструкция будет добавлена позже</small></div><button type="button" class="icon-btn primary-btn" data-start-training><span>Перейти к тренировке</span></button></section>
      <section class="gm06-training" data-training hidden><h3>Тренировочный пример</h3><p data-training-status></p><div class="gm06-buttons" data-training-buttons><button data-training-tone="low" aria-label="Низкий звук"></button><button data-training-tone="middle" aria-label="Средний звук"></button><button data-training-tone="high" aria-label="Высокий звук"></button></div></section>
      <section class="game-intro-new gm06-training-complete" data-training-complete hidden><h3>Обучение завершено</h3><p>Вы правильно повторили последовательность.</p><div class="gm06-training-actions"><button type="button" class="icon-btn gm06-training-repeat" data-repeat-training><span>Повторить тренировку</span></button><button type="button" class="icon-btn primary-btn" data-confirm-start><span>Начать игру</span></button></div></section>
      <section class="gm06-game" data-game hidden><p data-status></p><div class="gm06-buttons"><button data-tone="low" aria-label="Низкий звук"></button><button data-tone="middle" aria-label="Средний звук"></button><button data-tone="high" aria-label="Высокий звук"></button></div></section>
    </main><footer class="game-actions-new"><button type="button" data-close class="icon-btn"><span>К выбору игр</span></button></footer>`;

  const stage=container.querySelector('[data-stage]'),instruction=container.querySelector('[data-instruction]'),progress=container.querySelector('[data-progress]');
  const intro=container.querySelector('[data-intro]'),training=container.querySelector('[data-training]'),trainingStatus=container.querySelector('[data-training-status]'),trainingComplete=container.querySelector('[data-training-complete]'),trainingButtons=[...container.querySelectorAll('[data-training-tone]')];
  const game=container.querySelector('[data-game]'),status=container.querySelector('[data-status]'),buttons=[...container.querySelectorAll('[data-tone]')];
  let active=true,state=null,accepting=false,clicks=[],times=[],audio=null,playToken=0,trainingClicks=[];const timers=new Set();
  const wait=ms=>new Promise(resolve=>{const id=setTimeout(()=>{timers.delete(id);resolve()},ms);timers.add(id)});
  const context=()=>{audio??=new(window.AudioContext||window.webkitAudioContext)();return audio};
  function sound(name){const frequencies={low:330,middle:440,high:550},ctx=context(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=frequencies[name];gain.gain.setValueAtTime(.16,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.22);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.23)}
  function flash(name,targetButtons=buttons){const button=targetButtons.find(item=>(item.dataset.tone||item.dataset.trainingTone)===name);if(!button)return;button.classList.add('is-active');sound(name);const id=setTimeout(()=>{timers.delete(id);button.classList.remove('is-active')},240);timers.add(id)}
  const showOnly=target=>[intro,training,trainingComplete,game].forEach(section=>{section.hidden=section!==target});

  async function playSequence(sequence,intervals,targetButtons,messageTarget,token){targetButtons.forEach(button=>button.disabled=true);messageTarget.textContent='Слушайте и запоминайте';await wait(500);for(let index=0;index<sequence.length;index+=1){if(!active||token!==playToken)return;flash(sequence[index],targetButtons);await wait(index<intervals.length?intervals[index]:450)}if(!active||token!==playToken)return;targetButtons.forEach(button=>button.disabled=false);messageTarget.textContent=`Повторите ${sequence.length} нажатия`}
  async function beginTraining(){await context().resume();const token=++playToken;stage.classList.remove('is-instruction-stage');showOnly(training);progress.textContent='2. Тренировка';instruction.textContent='Послушайте и повторите короткую последовательность.';trainingClicks=[];const sequence=['low','middle','low'],intervals=[520,520];trainingButtons.forEach(button=>{button.disabled=true;button.onclick=()=>{if(button.disabled||token!==playToken)return;const tone=button.dataset.trainingTone;flash(tone,trainingButtons);trainingClicks.push(tone);const position=trainingClicks.length-1;if(tone!==sequence[position]){trainingButtons.forEach(item=>item.disabled=true);trainingStatus.textContent='Последовательность неверная. Послушайте ещё раз.';setTimeout(()=>{if(active&&token===playToken)beginTraining()},700);return}if(trainingClicks.length===sequence.length){trainingButtons.forEach(item=>item.disabled=true);trainingStatus.textContent='Верно.';setTimeout(()=>{if(!active||token!==playToken)return;showOnly(trainingComplete);progress.textContent='Обучение завершено';instruction.textContent='Тренировочный пример выполнен правильно.'},450)}}});await playSequence(sequence,intervals,trainingButtons,trainingStatus,token)}

  async function play(payload){const token=++playToken;accepting=false;await playSequence(payload.sequence,payload.intervals_ms,buttons,status,token);if(!active||token!==playToken)return;clicks=[];times=[];accepting=true}
  async function render(payload){state=payload;progress.textContent=`Цикл ${payload.round} из ${payload.round_count} · длина ${payload.sequence_length}`;await play(payload)}
  buttons.forEach(button=>button.onclick=async()=>{if(!accepting)return;flash(button.dataset.tone);clicks.push(button.dataset.tone);times.push(performance.now());if(clicks.length<state.sequence_length)return;accepting=false;buttons.forEach(item=>item.disabled=true);const intervals=times.slice(1).map((value,index)=>value-times[index]);status.textContent='Проверяю…';try{const next=await api.answer({session_id:state.session_id,selected_sequence:clicks,selected_intervals_ms:intervals});if(next.finished){progress.textContent='Завершено';status.textContent=`Точно повторено серий: ${Math.round(next.metrics.m08_series_accuracy*100)}%`;return}status.textContent=next.correct?'Верно':'Последовательность отличалась';await wait(700);await render(next)}catch(error){status.textContent=`Не удалось проверить ответ: ${error.message}`}});
  async function beginGame(){await context().resume();playToken+=1;showOnly(game);progress.textContent='Подготовка…';instruction.textContent='Послушайте и повторите последовательность кнопками.';try{await render(await api.start())}catch(error){status.textContent=`Не удалось начать игру: ${error.message}`}}

  container.querySelector('[data-start-training]').onclick=beginTraining;container.querySelector('[data-repeat-training]').onclick=beginTraining;container.querySelector('[data-confirm-start]').onclick=beginGame;container.querySelector('[data-close]').onclick=()=>{active=false;accepting=false;playToken+=1;timers.forEach(id=>clearTimeout(id));timers.clear();if(audio)audio.close();close()};
  const style=document.createElement('style');style.textContent=`
    .gm06-stage{text-align:center;overflow:hidden}.gm06-stage.is-instruction-stage{align-items:start;padding-top:clamp(14px,2.4vh,30px)}.gm06-intro,.gm06-training,.gm06-game{width:min(800px,100%)}.gm06-intro h3,.gm06-training h3{margin:0 0 10px;font-size:clamp(19px,2.3vw,25px)}.gm06-intro ol{width:min(700px,100%);margin:0 auto 16px;padding-left:28px;color:#52606d;text-align:left;font-size:clamp(14px,1.6vw,18px);line-height:1.4}.gm06-intro li+li{margin-top:5px}.gm06-example-title{margin:0 0 7px;font-weight:700}
    .gm06-media-placeholder{box-sizing:border-box;display:flex;width:min(620px,100%);height:clamp(130px,22vh,230px);margin:0 auto 18px;flex-direction:column;align-items:center;justify-content:center;gap:7px;border:2px dashed #b8cbd5;border-radius:16px;background:#eaf1f4;color:#52606d}.gm06-media-placeholder>span{display:grid;width:46px;height:46px;place-items:center;border-radius:50%;background:#d3e2e9;color:#168ba8}.gm06-media-placeholder strong{color:#263744}
    .gm06-training>p,.gm06-game>p{margin:0 0 14px;color:#52606d}.gm06-buttons{display:flex;gap:clamp(18px,4vw,46px);justify-content:center;margin:clamp(18px,4vh,38px)}.gm06-buttons button{width:clamp(110px,16vw,190px);aspect-ratio:1;border-radius:50%;border:6px solid rgba(23,33,43,.18);box-shadow:0 14px 28px rgba(20,35,45,.18);transition:transform .12s,filter .12s}.gm06-buttons button:nth-child(1){background:#61b8e8}.gm06-buttons button:nth-child(2){background:#76cf8b}.gm06-buttons button:nth-child(3){background:#e98c9a}.gm06-buttons button.is-active{transform:scale(.91);filter:brightness(1.35);box-shadow:0 0 0 10px rgba(56,169,199,.2)}
    .gm06-training-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.gm06-training-repeat{border-color:#60727d;background:#fff;color:#17212b}.gm06-training-repeat span{color:#17212b}.gm06-intro[hidden],.gm06-training[hidden],.gm06-training-complete[hidden],.gm06-game[hidden]{display:none}@media(max-height:700px){.gm06-stage.is-instruction-stage{padding-top:8px}.gm06-intro ol{margin-bottom:7px;font-size:13px;line-height:1.25}.gm06-media-placeholder{height:clamp(100px,18vh,140px);margin-bottom:8px}.gm06-buttons button{width:min(22vh,130px)}}
  `;container.append(style);return()=>{active=false;accepting=false;playToken+=1;timers.forEach(id=>clearTimeout(id));timers.clear();if(audio)audio.close()}
}
