export function mount({container,definition,api,close}){
  const trainingShapes={"треугольники":"triangle","воздушные шары":"balloon","силуэты птиц":"bird"};
  const trainingShape=trainingShapes[definition.selected_stimulus_set]||"triangle";
  container.innerHTML=`
    <header class="game-header-new"><div><p class="game-kicker-new mono">ВНИМАНИЕ</p><h2>${definition.title}</h2><p data-instruction>Запомните подсвеченные цели и следите за ними во время движения.</p></div><div class="game-progress-new" data-progress>Инструкция</div></header>
    <main class="game-stage-new gm09-stage is-instruction-stage" data-stage>
      <section class="gm09-intro" data-intro><h3>Как выполнять задание</h3><ol><li>Перед движением один или несколько объектов подсветятся жёлтым.</li><li>Следите за подсвеченными объектами, когда все фигуры начнут двигаться.</li><li>После остановки выберите эти объекты и нажмите «Готово».</li></ol><p class="gm09-example-title">Посмотрите пример</p><div class="gm09-media-placeholder"><span aria-hidden="true">▶</span><strong>Здесь будет GIF с примером</strong><small>Визуальная инструкция будет добавлена позже</small></div><button type="button" class="icon-btn primary-btn" data-start-training><span>Перейти к тренировке</span></button></section>
      <section class="gm09-training" data-training hidden><h3>Тренировочный пример</h3><p data-training-status></p><div class="gm09-field gm09-training-field" data-training-field></div><button type="button" class="icon-btn primary-btn" data-training-submit hidden><span>Готово</span></button></section>
      <section class="game-intro-new gm09-training-complete" data-training-complete hidden><h3>Обучение завершено</h3><p>Вы правильно отследили подсвеченный объект.</p><div class="gm09-training-actions"><button type="button" class="icon-btn gm09-training-repeat" data-repeat-training><span>Повторить тренировку</span></button><button type="button" class="icon-btn primary-btn" data-confirm-start><span>Начать игру</span></button></div></section>
      <section class="gm09-game" data-game hidden><div data-field class="gm09-field"></div><p data-status></p><button type="button" data-submit class="icon-btn primary-btn" hidden><span>Готово</span></button></section>
    </main><footer class="game-actions-new"><button type="button" data-close class="icon-btn"><span>К выбору игр</span></button></footer>`;
  const stage=container.querySelector('[data-stage]'),instruction=container.querySelector('[data-instruction]'),progress=container.querySelector('[data-progress]');
  const intro=container.querySelector('[data-intro]'),training=container.querySelector('[data-training]'),trainingField=container.querySelector('[data-training-field]'),trainingStatus=container.querySelector('[data-training-status]'),trainingSubmit=container.querySelector('[data-training-submit]'),trainingComplete=container.querySelector('[data-training-complete]');
  const game=container.querySelector('[data-game]'),field=container.querySelector('[data-field]'),status=container.querySelector('[data-status]'),submit=container.querySelector('[data-submit]');
  let active=true,state=null,selected=new Set(),selecting=false,renderToken=0;const timers=new Set();
  const wait=ms=>new Promise(resolve=>{const id=setTimeout(()=>{timers.delete(id);resolve()},ms);timers.add(id)});const showOnly=target=>[intro,training,trainingComplete,game].forEach(section=>{section.hidden=section!==target});
  function makeObject(item,shape,targets=[]){const button=document.createElement('button');button.type='button';button.className=`gm09-object shape-${shape}`;button.dataset.id=item.id;button.style.left=`${item.start[0]}%`;button.style.top=`${item.start[1]}%`;if(targets.includes(item.id))button.classList.add('is-target');return button}
  function moveObjects(target,objects,duration){[...target.children].forEach((node,index)=>{node.classList.remove('is-target');node.style.transition=`left ${duration}ms cubic-bezier(.45,.05,.55,.95),top ${duration}ms cubic-bezier(.45,.05,.55,.95)`;node.style.left=`${objects[index].end[0]}%`;node.style.top=`${objects[index].end[1]}%`})}

  async function beginTraining(){
    const token=++renderToken;stage.classList.remove('is-instruction-stage');showOnly(training);progress.textContent='Тренировка';instruction.textContent='Следите за жёлтым объектом.';trainingSubmit.hidden=true;trainingStatus.textContent='Запомните подсвеченный объект';
    const objects=[{id:'a',start:[18,25],end:[78,28]},{id:'target',start:[48,25],end:[22,72]},{id:'c',start:[78,25],end:[52,74]},{id:'d',start:[32,72],end:[78,72]}];trainingField.replaceChildren(...objects.map(item=>makeObject(item,trainingShape,['target'])));await wait(1400);if(!active||token!==renderToken)return;moveObjects(trainingField,objects,1800);trainingStatus.textContent='Следите за целью';await wait(1950);if(!active||token!==renderToken)return;
    let choice=null;trainingStatus.textContent='Выберите объект, который был подсвечен';[...trainingField.children].forEach(node=>node.onclick=()=>{[...trainingField.children].forEach(item=>item.classList.remove('is-selected'));node.classList.add('is-selected');choice=node.dataset.id;trainingSubmit.hidden=false});trainingSubmit.onclick=()=>{trainingSubmit.disabled=true;if(choice==='target'){trainingField.querySelector('[data-id="target"]').classList.add('is-correct');trainingStatus.textContent='Верно.';setTimeout(()=>{if(!active||token!==renderToken)return;showOnly(trainingComplete);progress.textContent='Обучение завершено';instruction.textContent='Тренировочный пример выполнен правильно.'},450);return}const wrong=trainingField.querySelector(`[data-id="${choice}"]`);if(wrong)wrong.classList.add('is-wrong');trainingStatus.textContent='Выбран другой объект. Посмотрите пример ещё раз.';setTimeout(()=>{if(active&&token===renderToken)beginTraining()},800)};trainingSubmit.disabled=false;
  }

  async function render(payload){const token=++renderToken;if(!active)return;state=payload;selected=new Set();selecting=false;submit.hidden=true;progress.textContent=`Раунд ${payload.round} из ${payload.round_count}`;status.textContent='Запомните подсвеченные объекты';field.replaceChildren(...payload.objects.map(item=>makeObject(item,payload.shape,payload.targets)));await wait(payload.preview_ms);if(!active||token!==renderToken)return;moveObjects(field,payload.objects,payload.movement_ms);status.textContent='Следите за целями';await wait(payload.movement_ms+150);if(!active||token!==renderToken)return;selecting=true;status.textContent=`Выберите ${payload.target_count} объекта`;[...field.children].forEach(node=>node.onclick=()=>{if(!selecting)return;const id=node.dataset.id;if(selected.has(id)){selected.delete(id);node.classList.remove('is-selected')}else if(selected.size<payload.target_count){selected.add(id);node.classList.add('is-selected')}submit.hidden=selected.size!==payload.target_count})}
  submit.onclick=async()=>{if(!selecting)return;selecting=false;submit.disabled=true;try{const next=await api.answer({session_id:state.session_id,selected:[...selected]});submit.disabled=false;if(next.finished){field.replaceChildren();submit.hidden=true;progress.textContent='Завершено';status.textContent=`Точность отслеживания: ${Math.round(next.metrics.a06_tracking_accuracy*100)}%`;return}status.textContent=next.correct?'Верно':'Цели выбраны неточно';await wait(650);await render(next)}catch(error){status.textContent=`Не удалось проверить ответ: ${error.message}`;submit.disabled=false}};
  async function beginGame(){renderToken+=1;showOnly(game);progress.textContent='Подготовка…';instruction.textContent='Запомните подсвеченные цели и следите за ними.';try{await render(await api.start())}catch(error){status.textContent=`Не удалось начать игру: ${error.message}`}}

  container.querySelector('[data-start-training]').onclick=beginTraining;container.querySelector('[data-repeat-training]').onclick=beginTraining;container.querySelector('[data-confirm-start]').onclick=beginGame;container.querySelector('[data-close]').onclick=()=>{active=false;renderToken+=1;timers.forEach(id=>clearTimeout(id));timers.clear();close()};
  const style=document.createElement('style');style.textContent=`
    .gm09-stage{text-align:center}.gm09-stage.is-instruction-stage{align-items:start;padding-top:clamp(14px,2.4vh,30px)}.gm09-intro,.gm09-training,.gm09-game{width:min(900px,100%)}.gm09-intro h3,.gm09-training h3{margin:0 0 10px;font-size:clamp(19px,2.3vw,25px)}.gm09-intro ol{width:min(700px,100%);margin:0 auto 16px;padding-left:28px;color:#52606d;text-align:left;font-size:clamp(14px,1.6vw,18px);line-height:1.4}.gm09-intro li+li{margin-top:5px}.gm09-example-title{margin:0 0 7px;font-weight:700}
    .gm09-media-placeholder{box-sizing:border-box;display:flex;width:min(620px,100%);height:clamp(130px,22vh,230px);margin:0 auto 18px;flex-direction:column;align-items:center;justify-content:center;gap:7px;border:2px dashed #b8cbd5;border-radius:16px;background:#eaf1f4;color:#52606d}.gm09-media-placeholder>span{display:grid;width:46px;height:46px;place-items:center;border-radius:50%;background:#d3e2e9;color:#168ba8}.gm09-media-placeholder strong{color:#263744}.gm09-training>p,.gm09-game>p{margin:0 0 8px;color:#52606d}
    .gm09-field{position:relative;width:min(78vw,850px);height:min(50vh,480px);margin:0 auto 12px;border:1px solid #b8c8d1;border-radius:22px;background:#eef3f5;overflow:hidden}.gm09-training-field{width:min(700px,85vw);height:min(42vh,400px)}.gm09-object{position:absolute;width:58px;height:58px;transform:translate(-50%,-50%);border:4px solid #23313d;background:#fff}.gm09-object:hover:not(:disabled),.gm09-object:active:not(:disabled),.gm09-object:focus-visible{transform:translate(-50%,-50%)}.shape-circle{border-radius:50%}.shape-triangle{clip-path:polygon(50% 5%,95% 92%,5% 92%)}.shape-balloon{border-radius:50% 50% 46% 46%}.gm09-object.is-target{background:#f0be3d;box-shadow:0 0 0 8px rgba(240,190,61,.25)}.gm09-object.is-selected{background:#38a9c7;box-shadow:0 0 0 7px rgba(56,169,199,.22)}.gm09-object.is-correct{border-color:#1d9b69;background:#61c79b}.gm09-object.is-wrong{border-color:#d64b59;background:#f3a4ad}
    .shape-bird{width:66px;height:42px;border-radius:50%;clip-path:polygon(0 55%,22% 35%,45% 48%,62% 18%,100% 45%,65% 62%,45% 55%,20% 72%)}
    .gm09-training-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.gm09-training-repeat{border-color:#60727d;background:#fff;color:#17212b}.gm09-training-repeat span{color:#17212b}.gm09-intro[hidden],.gm09-training[hidden],.gm09-training-complete[hidden],.gm09-game[hidden]{display:none}@media(max-height:700px){.gm09-stage.is-instruction-stage{padding-top:8px}.gm09-intro ol{margin-bottom:7px;font-size:13px;line-height:1.25}.gm09-media-placeholder{height:clamp(100px,18vh,140px);margin-bottom:8px}.gm09-field{height:min(42vh,360px)}}
  `;container.append(style);return()=>{active=false;selecting=false;renderToken+=1;timers.forEach(id=>clearTimeout(id));timers.clear()}
}
