const TRIAL_SLOT_MS=1500;
export function mount({container,definition,api,close}){
  const signalLabels={"буква В":{symbol:"В",name:"букву «В»"},"геометрические фигуры":{symbol:"◢",name:"фигуру"},"цифра 1":{symbol:"1",name:"цифру «1»"}};
  const selectedSignal=signalLabels[definition.selected_stimulus_set]||signalLabels["буква В"];
  container.innerHTML=`
    <header class="game-header-new"><div><p class="game-kicker-new mono">ВНИМАНИЕ</p><h2>${definition.title}</h2><p data-instruction>Нажимайте на обычный сигнал и не нажимайте на зеркальный.</p></div><div class="game-progress-new" data-progress>Инструкция</div></header>
    <main class="game-stage-new gm08-module is-instruction-stage" data-stage>
      <section class="gm08-intro" data-intro><h3>Как выполнять задание</h3><ol><li>Если появилась обычная ${selectedSignal.name}, нажмите на неё или клавишу пробела.</li><li>Если сигнал зеркальный, ничего не нажимайте.</li><li>Отвечайте быстро, но внимательно различайте сигналы.</li></ol><p class="gm08-example-title">Посмотрите пример</p><div class="gm08-media-placeholder"><span aria-hidden="true">▶</span><strong>Здесь будет GIF с примером</strong><small>Визуальная инструкция будет добавлена позже</small></div><button type="button" class="icon-btn primary-btn" data-start-training><span>Перейти к тренировке</span></button></section>
      <section class="gm08-training" data-training hidden><h3>Тренировочный пример</h3><p data-training-status></p><button type="button" class="gm08-module-stimulus" data-training-stimulus hidden aria-label="Ответить">${selectedSignal.symbol}</button></section>
      <section class="game-intro-new gm08-training-complete" data-training-complete hidden><h3>Обучение завершено</h3><p>Вы правильно ответили на обычный сигнал и удержались при стоп-сигнале.</p><div class="gm08-training-actions"><button type="button" class="icon-btn gm08-training-repeat" data-repeat-training><span>Повторить тренировку</span></button><button type="button" class="icon-btn primary-btn" data-confirm-start><span>Начать игру</span></button></div></section>
      <section class="gm08-game" data-game hidden><button type="button" class="gm08-module-stimulus" data-stimulus hidden aria-label="Ответить">${selectedSignal.symbol}</button><div class="game-result-new" data-result hidden><h3>Игра завершена</h3><p data-result-text></p><button type="button" class="icon-btn primary-btn" data-restart><span>Ещё раз</span></button></div></section>
    </main><footer class="game-actions-new"><button type="button" class="icon-btn" data-close><span>К выбору игр</span></button></footer>`;
  const stage=container.querySelector('[data-stage]'),instruction=container.querySelector('[data-instruction]'),progress=container.querySelector('[data-progress]');
  const intro=container.querySelector('[data-intro]'),training=container.querySelector('[data-training]'),trainingStatus=container.querySelector('[data-training-status]'),trainingStimulus=container.querySelector('[data-training-stimulus]'),trainingComplete=container.querySelector('[data-training-complete]');
  const game=container.querySelector('[data-game]'),stimulus=container.querySelector('[data-stimulus]'),result=container.querySelector('[data-result]'),resultText=container.querySelector('[data-result-text]'),restart=container.querySelector('[data-restart]');
  let state=null,accepting=false,acceptingTraining=false,responseTimer=null,shownAt=0,token=0,active=true,trainingStep=0;const timers=new Set();
  const delay=milliseconds=>new Promise(resolve=>{const id=setTimeout(()=>{timers.delete(id);resolve()},milliseconds);timers.add(id)});
  const showOnly=target=>[intro,training,trainingComplete,game].forEach(section=>{section.hidden=section!==target});
  const clearResponse=()=>{clearTimeout(responseTimer);timers.delete(responseTimer);responseTimer=null};

  function beginTraining(){token+=1;clearResponse();stage.classList.remove('is-instruction-stage');showOnly(training);progress.textContent='Тренировка';instruction.textContent='Ответьте на обычную букву и не нажимайте на зеркальную.';trainingStep=0;showTrainingSignal(token)}
  function showTrainingSignal(currentToken){if(!active||currentToken!==token)return;clearResponse();acceptingTraining=true;trainingStimulus.hidden=false;trainingStimulus.classList.toggle('is-mirrored',trainingStep===1);trainingStatus.textContent=trainingStep===0?'Обычный сигнал: нажмите':'Стоп-сигнал: ничего не нажимайте';responseTimer=setTimeout(()=>{timers.delete(responseTimer);responseTimer=null;if(!active||currentToken!==token||!acceptingTraining)return;acceptingTraining=false;trainingStimulus.hidden=true;if(trainingStep===0){failTraining(currentToken,'На обычный сигнал нужно нажать.')}else{trainingStatus.textContent='Верно, вы не нажали на стоп-сигнал.';setTimeout(()=>finishTraining(currentToken),450)}},trainingStep===0?1800:1400);timers.add(responseTimer)}
  function trainingRespond(){if(!acceptingTraining)return;acceptingTraining=false;clearResponse();trainingStimulus.hidden=true;if(trainingStep===1){failTraining(token,'На зеркальную букву нажимать нельзя.');return}trainingStatus.textContent='Верно. Теперь приготовьтесь к стоп-сигналу.';trainingStep=1;const currentToken=token;setTimeout(()=>showTrainingSignal(currentToken),550)}
  function failTraining(currentToken,message){trainingStatus.textContent=`${message} Попробуем ещё раз.`;const id=setTimeout(()=>{timers.delete(id);if(active&&currentToken===token)beginTraining()},850);timers.add(id)}
  function finishTraining(currentToken){if(!active||currentToken!==token)return;showOnly(trainingComplete);progress.textContent='Обучение завершено';instruction.textContent='Тренировочный пример выполнен правильно.'}

  async function renderTrial(payload){const currentToken=++token;state=payload;accepting=false;clearResponse();progress.textContent=`Стимул ${payload.trial} из ${payload.trial_count}`;result.hidden=true;stimulus.hidden=true;await delay(220);if(!active||currentToken!==token)return;stimulus.textContent=payload.symbol;stimulus.classList.toggle('is-mirrored',payload.mirrored);stimulus.hidden=false;shownAt=performance.now();accepting=true;responseTimer=setTimeout(()=>respond(false),payload.display_ms);timers.add(responseTimer)}
  async function respond(responded){if(!accepting||!state)return;accepting=false;clearResponse();const reaction=responded?performance.now()-shownAt:null;stimulus.hidden=true;const elapsed=performance.now()-shownAt;if(elapsed<TRIAL_SLOT_MS)await delay(TRIAL_SLOT_MS-elapsed);if(!active)return;try{const payload=await api.answer({session_id:state.session_id,responded,reaction_ms:reaction,timestamp_ms:Date.now()});if(!active)return;if(!payload.finished){await renderTrial(payload);return}result.hidden=false;restart.disabled=false;progress.textContent='Завершено';instruction.textContent='Все 40 стимулов завершены.';resultText.textContent=`Ошибок: ${payload.metrics.u07_error_count}.`}catch(error){instruction.textContent=`Не удалось сохранить ответ: ${error.message}`;accepting=true;stimulus.hidden=false}}
  async function begin(){token+=1;accepting=false;acceptingTraining=false;clearResponse();restart.disabled=true;showOnly(game);// Надпись ставится один раз на всё задание: её смена в момент
    // появления сигнала отвлекала именно тогда, когда нужно реагировать.
    instruction.textContent='Нажимайте только на обычный сигнал.';try{await renderTrial(await api.start())}catch(error){instruction.textContent=`Не удалось начать игру: ${error.message}`;restart.disabled=false}}
  function onKeyDown(event){if(event.code!=='Space')return;if(acceptingTraining){event.preventDefault();trainingRespond();return}if(accepting){event.preventDefault();respond(true)}}

  trainingStimulus.onclick=trainingRespond;stimulus.onclick=()=>respond(true);container.querySelector('[data-start-training]').onclick=beginTraining;container.querySelector('[data-repeat-training]').onclick=beginTraining;container.querySelector('[data-confirm-start]').onclick=begin;restart.onclick=begin;window.addEventListener('keydown',onKeyDown);container.querySelector('[data-close]').onclick=()=>{active=false;token+=1;accepting=false;acceptingTraining=false;clearResponse();timers.forEach(id=>clearTimeout(id));timers.clear();window.removeEventListener('keydown',onKeyDown);close()};
  const style=document.createElement('style');style.textContent=`
    .gm08-module{text-align:center}.gm08-module.is-instruction-stage{align-items:start;padding-top:clamp(14px,2.4vh,30px)}.gm08-intro,.gm08-training,.gm08-game{width:min(800px,100%)}.gm08-intro h3,.gm08-training h3{margin:0 0 10px;font-size:clamp(19px,2.3vw,25px)}.gm08-intro ol{width:min(700px,100%);margin:0 auto 16px;padding-left:28px;color:#52606d;text-align:left;font-size:clamp(14px,1.6vw,18px);line-height:1.4}.gm08-intro li+li{margin-top:5px}.gm08-example-title{margin:0 0 7px;font-weight:700}
    .gm08-media-placeholder{box-sizing:border-box;display:flex;width:min(620px,100%);height:clamp(130px,22vh,230px);margin:0 auto 18px;flex-direction:column;align-items:center;justify-content:center;gap:7px;border:2px dashed #b8cbd5;border-radius:16px;background:#eaf1f4;color:#52606d}.gm08-media-placeholder>span{display:grid;width:46px;height:46px;place-items:center;border-radius:50%;background:#d3e2e9;color:#168ba8}.gm08-media-placeholder strong{color:#263744}.gm08-training>p{margin:0 0 16px;color:#52606d}
    .gm08-module-stimulus{width:min(300px,45vh,60vw);aspect-ratio:1;border:2px solid #c8d7de;border-radius:28px;background:#fff;color:#17212b;font-size:clamp(100px,24vh,210px);font-weight:800;box-shadow:0 14px 28px rgba(20,35,45,.12)}.gm08-module-stimulus[hidden]{display:none}.gm08-module-stimulus.is-mirrored{transform:scaleX(-1)}.gm08-training-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.gm08-training-repeat{border-color:#60727d;background:#fff;color:#17212b}.gm08-training-repeat span{color:#17212b}.gm08-intro[hidden],.gm08-training[hidden],.gm08-training-complete[hidden],.gm08-game[hidden]{display:none}@media(max-height:700px){.gm08-module.is-instruction-stage{padding-top:8px}.gm08-intro ol{margin-bottom:7px;font-size:13px;line-height:1.25}.gm08-media-placeholder{height:clamp(100px,18vh,140px);margin-bottom:8px}.gm08-module-stimulus{width:min(250px,38vh)}}
  `;container.append(style);return()=>{active=false;token+=1;accepting=false;acceptingTraining=false;clearResponse();timers.forEach(id=>clearTimeout(id));timers.clear();window.removeEventListener('keydown',onKeyDown)}
}
