export function mount({container,definition,api,close}){
  container.innerHTML=`
    <header class="game-header-new"><div><p class="game-kicker-new mono">ПАМЯТЬ</p><h2>${definition.title}</h2><p data-instruction>Запомните подсвеченные клетки, затем отметьте их.</p></div><div class="game-progress-new" data-progress>1. Инструкция</div></header>
    <main class="game-stage-new gm04-stage is-instruction-stage" data-stage>
      <section class="gm04-intro" data-intro><h3>Как выполнять задание</h3><ol><li>Несколько клеток одновременно подсветятся.</li><li>Запомните расположение всех подсвеченных клеток.</li><li>Когда подсветка исчезнет, отметьте те же клетки и нажмите «Готово».</li></ol><p class="gm04-example-title">Посмотрите пример</p><div class="gm04-media-placeholder"><span aria-hidden="true">▶</span><strong>Здесь будет GIF с примером</strong><small>Визуальная инструкция будет добавлена позже</small></div><button type="button" class="icon-btn primary-btn" data-start-training><span>Перейти к тренировке</span></button></section>
      <section class="gm04-training" data-training hidden><h3>Тренировочный пример</h3><p data-training-status></p><div class="gm04-grid gm04-training-grid" data-training-grid></div><button type="button" class="icon-btn primary-btn" data-training-submit hidden><span>Готово</span></button></section>
      <section class="game-intro-new gm04-training-complete" data-training-complete hidden><h3>Обучение завершено</h3><p>Вы правильно воспроизвели расположение клеток.</p><div class="gm04-training-actions"><button type="button" class="icon-btn gm04-training-repeat" data-repeat-training><span>Повторить тренировку</span></button><button type="button" class="icon-btn primary-btn" data-confirm-start><span>Начать игру</span></button></div></section>
      <section class="gm04-game" data-game hidden><p data-round></p><div data-grid class="gm04-grid"></div><p data-status></p><button type="button" data-submit class="icon-btn primary-btn" hidden><span>Готово</span></button></section>
    </main><footer class="game-actions-new"><button type="button" data-close class="icon-btn"><span>К выбору игр</span></button></footer>`;

  const stage=container.querySelector('[data-stage]'),instruction=container.querySelector('[data-instruction]'),progress=container.querySelector('[data-progress]');
  const intro=container.querySelector('[data-intro]'),training=container.querySelector('[data-training]'),trainingGrid=container.querySelector('[data-training-grid]'),trainingStatus=container.querySelector('[data-training-status]'),trainingSubmit=container.querySelector('[data-training-submit]'),trainingComplete=container.querySelector('[data-training-complete]');
  const game=container.querySelector('[data-game]'),grid=container.querySelector('[data-grid]'),round=container.querySelector('[data-round]'),status=container.querySelector('[data-status]'),submit=container.querySelector('[data-submit]');
  let active=true,state=null,selected=new Set(),trainingSelected=new Set(),phaseToken=0;const intervals=new Set(),timers=new Set();
  const later=(callback,delay)=>{const id=setTimeout(()=>{timers.delete(id);callback()},delay);timers.add(id)};
  const showOnly=target=>[intro,training,trainingComplete,game].forEach(section=>{section.hidden=section!==target});
  function clearRunning(){intervals.forEach(id=>clearInterval(id));intervals.clear();timers.forEach(id=>clearTimeout(id));timers.clear()}
  function build(target,size,clickHandler){target.style.gridTemplateColumns=`repeat(${size},1fr)`;target.replaceChildren(...Array.from({length:size*size},(_,index)=>{const button=document.createElement('button');button.type='button';button.className='gm04-cell';button.dataset.index=index;if(clickHandler)button.onclick=()=>clickHandler(index,button);return button}))}

  function beginTraining(){clearRunning();const token=++phaseToken;stage.classList.remove('is-instruction-stage');showOnly(training);progress.textContent='2. Тренировка';instruction.textContent='Запомните расположение подсвеченных клеток.';trainingSelected=new Set();trainingSubmit.hidden=true;build(trainingGrid,3);const targets=[0,4,8];targets.forEach(index=>trainingGrid.children[index].classList.add('is-target'));let left=3;trainingStatus.textContent=`Запоминайте: ${left}`;const id=setInterval(()=>{if(!active||token!==phaseToken){clearInterval(id);intervals.delete(id);return}left-=1;trainingStatus.textContent=`Запоминайте: ${left}`;if(left<=0){clearInterval(id);intervals.delete(id);beginTrainingRecall(token,targets)}},1000);intervals.add(id)}
  function beginTrainingRecall(token,targets){if(!active||token!==phaseToken)return;trainingSelected=new Set();build(trainingGrid,3,(index,button)=>{trainingSelected.has(index)?trainingSelected.delete(index):trainingSelected.add(index);button.classList.toggle('is-selected',trainingSelected.has(index))});trainingStatus.textContent='Отметьте три клетки из показанного набора.';trainingSubmit.hidden=false;trainingSubmit.disabled=false;trainingSubmit.onclick=()=>{trainingSubmit.disabled=true;const answer=[...trainingSelected].sort((a,b)=>a-b);const correct=answer.length===targets.length&&answer.every((value,index)=>value===targets[index]);if(correct){answer.forEach(index=>trainingGrid.children[index].classList.add('is-correct'));trainingStatus.textContent='Верно.';later(()=>{if(!active||token!==phaseToken)return;showOnly(trainingComplete);progress.textContent='Обучение завершено';instruction.textContent='Тренировочный пример выполнен правильно.'},450);return}trainingStatus.textContent='Расположение воспроизведено неверно. Посмотрите образец ещё раз.';[...trainingGrid.children].forEach(button=>button.classList.add('is-wrong'));later(()=>{if(active&&token===phaseToken)beginTraining()},700)}}

  async function render(payload){if(!active)return;state=payload;selected=new Set();build(grid,payload.grid_size);round.textContent=`Раунд ${payload.round} из ${payload.round_count}`;status.textContent='';submit.hidden=true;if(payload.phase==='study'){payload.targets.forEach(index=>grid.children[index].classList.add('is-target'));let left=payload.study_seconds;status.textContent=`Запоминайте: ${left}`;const token=phaseToken;const id=setInterval(async()=>{if(!active||token!==phaseToken){clearInterval(id);intervals.delete(id);return}left-=1;status.textContent=`Запоминайте: ${left}`;if(left<=0){clearInterval(id);intervals.delete(id);try{await render(await api.answer({session_id:payload.session_id,action:'begin_recall'}))}catch(error){status.textContent=`Не удалось продолжить: ${error.message}`}}},1000);intervals.add(id);return}[...grid.children].forEach((button,index)=>button.onclick=()=>{selected.has(index)?selected.delete(index):selected.add(index);button.classList.toggle('is-selected',selected.has(index))});status.textContent='Отметьте все клетки из показанного набора.';submit.hidden=false}
  submit.onclick=async()=>{submit.disabled=true;try{const payload=await api.answer({session_id:state.session_id,selected:[...selected]});if(payload.finished){grid.replaceChildren();submit.hidden=true;progress.textContent='Завершено';status.textContent=`Правильно воспроизведено: ${Math.round(payload.metrics.m07_target_recognition_rate*100)}%`;return}await render(payload)}catch(error){status.textContent=`Не удалось проверить ответ: ${error.message}`}finally{submit.disabled=false}};
  async function beginGame(){clearRunning();phaseToken+=1;showOnly(game);progress.textContent='Подготовка…';instruction.textContent='Запомните подсвеченные клетки, затем отметьте их.';try{await render(await api.start())}catch(error){status.textContent=`Не удалось начать игру: ${error.message}`}}

  container.querySelector('[data-start-training]').onclick=beginTraining;container.querySelector('[data-repeat-training]').onclick=beginTraining;container.querySelector('[data-confirm-start]').onclick=beginGame;container.querySelector('[data-close]').onclick=()=>{active=false;phaseToken+=1;clearRunning();close()};
  const style=document.createElement('style');style.textContent=`
    .gm04-stage{text-align:center;overflow:hidden}.gm04-stage.is-instruction-stage{align-items:start;padding-top:clamp(14px,2.4vh,30px)}.gm04-intro,.gm04-training,.gm04-game{width:min(800px,100%)}.gm04-intro h3,.gm04-training h3{margin:0 0 10px;font-size:clamp(19px,2.3vw,25px)}.gm04-intro ol{width:min(700px,100%);margin:0 auto 16px;padding-left:28px;color:#52606d;text-align:left;font-size:clamp(14px,1.6vw,18px);line-height:1.4}.gm04-intro li+li{margin-top:5px}.gm04-example-title{margin:0 0 7px;font-weight:700}
    .gm04-media-placeholder{box-sizing:border-box;display:flex;width:min(620px,100%);height:clamp(130px,22vh,230px);margin:0 auto 18px;flex-direction:column;align-items:center;justify-content:center;gap:7px;border:2px dashed #b8cbd5;border-radius:16px;background:#eaf1f4;color:#52606d}.gm04-media-placeholder>span{display:grid;width:46px;height:46px;place-items:center;border-radius:50%;background:#d3e2e9;color:#168ba8}.gm04-media-placeholder strong{color:#263744}
    .gm04-training>p,.gm04-game>p{margin:0 0 10px;color:#52606d}.gm04-grid{display:grid;gap:clamp(8px,1.5vh,12px);width:min(52vh,500px,72vw);margin:clamp(8px,1.5vh,20px) auto}.gm04-training-grid{width:min(45vh,390px,65vw)}.gm04-cell{aspect-ratio:1;border:1px solid #aebec8;border-radius:14px;background:#fff}.gm04-cell:hover{border-color:#38a9c7}.gm04-cell.is-target{background:linear-gradient(135deg,#87d9ec,#9d8de3);border-color:transparent}.gm04-cell.is-selected{background:#38a9c7;border-color:#247d97;box-shadow:inset 0 0 0 4px #d8f6ff}.gm04-cell.is-correct{background:#61c79b;border-color:#1d9b69}.gm04-cell.is-wrong{border-color:#d64b59}
    .gm04-training-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.gm04-training-repeat{border-color:#60727d;background:#fff;color:#17212b}.gm04-training-repeat span{color:#17212b}.gm04-intro[hidden],.gm04-training[hidden],.gm04-training-complete[hidden],.gm04-game[hidden]{display:none}@media(max-height:700px){.gm04-stage.is-instruction-stage{padding-top:8px}.gm04-intro ol{margin-bottom:7px;font-size:13px;line-height:1.25}.gm04-media-placeholder{height:clamp(100px,18vh,140px);margin-bottom:8px}.gm04-grid{width:min(48vh,410px,65vw);margin:6px auto}}
  `;container.append(style);return()=>{active=false;phaseToken+=1;clearRunning()}
}
