export function mount({container,definition,api,close}){
  const trainingExamples={
    "животные":{word:"кошка",picture:"cat.png",options:["собака","кошка","лиса","мышь"]},
    "еда":{word:"яблоко",picture:"apple.png",options:["груша","яблоко","хлеб","лимон"]},
    "предметы быта":{word:"чашка",picture:"cup.png",options:["ключ","лампа","чашка","книга"]},
  };
  const trainingExample=trainingExamples[definition.selected_stimulus_set]||trainingExamples["животные"];
  container.innerHTML=`
    <header class="game-header-new"><div><p class="game-kicker-new mono">РЕЧЬ</p><h2>${definition.title}</h2><p data-instruction>Посмотрите на картинку и выберите подходящее слово.</p></div><div class="game-progress-new" data-progress>Инструкция</div></header>
    <main class="game-stage-new gm12-module is-instruction-stage" data-stage>
      <section class="gm12-intro" data-intro><h3>Как выполнять задание</h3><ol><li>Рассмотрите показанное изображение.</li><li>Прочитайте четыре предложенных слова.</li><li>Нажмите слово, которое правильно называет изображённый предмет.</li></ol><p class="gm12-example-title">Посмотрите пример</p><div class="gm12-media-placeholder"><span aria-hidden="true">▶</span><strong>Здесь будет GIF с примером</strong><small>Визуальная инструкция будет добавлена позже</small></div><button type="button" class="icon-btn primary-btn" data-start-training><span>Перейти к тренировке</span></button></section>
      <section class="gm12-training" data-training hidden><h3>Тренировочный пример</h3><p>Выберите слово, которое соответствует картинке.</p><div class="gm12-module-picture"><img src="/game-assets/objects/${trainingExample.picture}" alt="${trainingExample.word}"></div><div class="gm12-module-options" data-training-options></div><p data-training-feedback aria-live="polite"></p></section>
      <section class="game-intro-new gm12-training-complete" data-training-complete hidden><h3>Обучение завершено</h3><p>Вы правильно соединили изображение и слово.</p><div class="gm12-training-actions"><button type="button" class="icon-btn gm12-training-repeat" data-repeat-training><span>Повторить тренировку</span></button><button type="button" class="icon-btn primary-btn" data-confirm-start><span>Начать игру</span></button></div></section>
      <section class="gm12-game" data-game hidden><div class="gm12-module-task" data-task hidden><div class="gm12-module-picture"><img data-picture alt="Изображение для выбора слова"></div><div class="gm12-module-options" data-options></div></div><div class="game-result-new" data-result hidden><h3>Игра завершена</h3><p data-result-text></p><button type="button" class="icon-btn primary-btn" data-restart><span>Ещё раз</span></button></div></section>
    </main><footer class="game-actions-new"><button type="button" class="icon-btn" data-close><span>К выбору игр</span></button></footer>`;
  const stage=container.querySelector('[data-stage]'),instruction=container.querySelector('[data-instruction]'),progress=container.querySelector('[data-progress]');
  const intro=container.querySelector('[data-intro]'),training=container.querySelector('[data-training]'),trainingOptions=container.querySelector('[data-training-options]'),trainingFeedback=container.querySelector('[data-training-feedback]'),trainingComplete=container.querySelector('[data-training-complete]');
  const game=container.querySelector('[data-game]'),task=container.querySelector('[data-task]'),picture=container.querySelector('[data-picture]'),options=container.querySelector('[data-options]'),result=container.querySelector('[data-result]'),resultText=container.querySelector('[data-result-text]'),restart=container.querySelector('[data-restart]');
  let state=null,accepting=false,active=true,token=0,deadline=0,timeoutId=null,clockId=null,requestInFlight=false,timeExpired=false;const timers=new Set();
  const delay=milliseconds=>new Promise(resolve=>{const id=setTimeout(()=>{timers.delete(id);resolve()},milliseconds);timers.add(id)});const showOnly=target=>[intro,training,trainingComplete,game].forEach(section=>{section.hidden=section!==target});
  function optionButton(word,handler){const button=document.createElement('button');button.type='button';button.className='gm12-module-option';button.textContent=word;button.onclick=()=>handler(word,button);return button}
  function beginTraining(){token+=1;stage.classList.remove('is-instruction-stage');showOnly(training);progress.textContent='Тренировка';instruction.textContent='Выберите название показанного предмета.';trainingFeedback.textContent='';trainingFeedback.className='';trainingOptions.replaceChildren(...trainingExample.options.map(word=>optionButton(word,(selected,button)=>{if(button.disabled)return;if(selected!==trainingExample.word){button.classList.add('is-incorrect');button.disabled=true;trainingFeedback.textContent='Это другое слово. Попробуйте ещё раз.';trainingFeedback.className='is-wrong';return}[...trainingOptions.children].forEach(item=>item.disabled=true);button.classList.add('is-correct');trainingFeedback.textContent='Верно.';trainingFeedback.className='is-correct';const currentToken=token;setTimeout(()=>{if(!active||currentToken!==token)return;showOnly(trainingComplete);progress.textContent='Обучение завершено';instruction.textContent='Тренировочный пример выполнен правильно.'},450)})))}

  function clearClock(){clearTimeout(timeoutId);clearInterval(clockId);timeoutId=null;clockId=null}function updateProgress(){const remaining=Math.max(0,deadline-performance.now()),seconds=Math.ceil(remaining/1000),minutes=Math.floor(seconds/60),rest=seconds%60;progress.textContent=`Задание ${state?.trial||1} · время ${minutes}:${String(rest).padStart(2,'0')}`}
  function startClock(durationMs){clearClock();timeExpired=false;deadline=performance.now()+durationMs;updateProgress();clockId=setInterval(updateProgress,250);timeoutId=setTimeout(()=>{timeExpired=true;updateProgress();if(!requestInFlight)finishByTime()},durationMs)}
  function renderTrial(payload){state=payload;accepting=true;updateProgress();instruction.textContent='Выберите слово, которое соответствует картинке.';picture.src=`/game-assets/objects/${encodeURIComponent(payload.picture)}`;picture.alt=`Картинка из категории «${payload.category}»`;options.replaceChildren(...payload.choices.map(word=>optionButton(word,answer)));result.hidden=true;task.hidden=false}
  async function answer(selectedWord,button){if(!accepting||!state)return;accepting=false;const currentToken=token;options.querySelectorAll('button').forEach(item=>{item.disabled=true;item.classList.toggle('is-selected',item.textContent===selectedWord)});requestInFlight=true;try{const payload=await api.answer({session_id:state.session_id,selected_word:selectedWord,timestamp_ms:Date.now()});if(!active||currentToken!==token)return;const correct=payload.finished?payload.correct:payload.previous_correct;button.classList.remove('is-selected');button.classList.add(correct?'is-correct':'is-incorrect');await delay(400);requestInFlight=false;if(!payload.finished){if(timeExpired){state=payload;await finishByTime();return}renderTrial(payload);return}showResult(payload)}catch(error){requestInFlight=false;instruction.textContent=`Не удалось сохранить ответ: ${error.message}`;accepting=true;options.querySelectorAll('button').forEach(item=>{item.disabled=false})}}
  function showResult(payload){clearClock();accepting=false;task.hidden=true;result.hidden=false;restart.disabled=false;const early=payload.completion_reason==='all_items';progress.textContent=early?'Задание выполнено':'Время завершено';instruction.textContent=early?'Все карточки пройдены.':'Минута закончилась.';const correctCount=payload.events.filter(event=>event.correct).length;resultText.textContent=`Выполнено: ${payload.events.length}. Правильных ответов: ${correctCount}.`}
  async function finishByTime(){if(!active||!state||requestInFlight)return;accepting=false;requestInFlight=true;options.querySelectorAll('button').forEach(button=>{button.disabled=true});try{const payload=await api.answer({session_id:state.session_id,time_up:true});if(active)showResult(payload)}catch(error){requestInFlight=false;instruction.textContent=`Не удалось завершить игру: ${error.message}`}}
  async function begin(){token+=1;accepting=false;requestInFlight=false;clearClock();restart.disabled=true;showOnly(game);task.hidden=true;result.hidden=true;instruction.textContent='Подготавливаю задание…';try{const payload=await api.start();renderTrial(payload);startClock(payload.duration_ms)}catch(error){instruction.textContent=`Не удалось начать игру: ${error.message}`;restart.disabled=false}}

  container.querySelector('[data-start-training]').onclick=beginTraining;container.querySelector('[data-repeat-training]').onclick=beginTraining;container.querySelector('[data-confirm-start]').onclick=begin;restart.onclick=begin;container.querySelector('[data-close]').onclick=()=>{active=false;accepting=false;token+=1;clearClock();timers.forEach(id=>clearTimeout(id));timers.clear();close()};
  const style=document.createElement('style');style.textContent=`
    .gm12-module{display:grid;place-items:center;text-align:center;overflow:hidden}.gm12-module.is-instruction-stage{align-items:start;padding-top:clamp(14px,2.4vh,30px)}.gm12-intro,.gm12-training,.gm12-game{width:min(800px,100%)}.gm12-intro h3,.gm12-training h3{margin:0 0 10px;font-size:clamp(19px,2.3vw,25px)}.gm12-intro ol{width:min(700px,100%);margin:0 auto 16px;padding-left:28px;color:#52606d;text-align:left;font-size:clamp(14px,1.6vw,18px);line-height:1.4}.gm12-intro li+li{margin-top:5px}.gm12-example-title{margin:0 0 7px;font-weight:700}
    .gm12-media-placeholder{box-sizing:border-box;display:flex;width:min(620px,100%);height:clamp(130px,22vh,230px);margin:0 auto 18px;flex-direction:column;align-items:center;justify-content:center;gap:7px;border:2px dashed #b8cbd5;border-radius:16px;background:#eaf1f4;color:#52606d}.gm12-media-placeholder>span{display:grid;width:46px;height:46px;place-items:center;border-radius:50%;background:#d3e2e9;color:#168ba8}.gm12-media-placeholder strong{color:#263744}.gm12-training>p{margin:0 0 10px;color:#52606d}.gm12-module-task{width:min(720px,94%);margin:auto}.gm12-module-task[hidden]{display:none}.gm12-module-picture{display:grid;place-items:center;width:min(250px,32vh,58vw);aspect-ratio:1;margin:0 auto clamp(14px,2.5vh,24px);padding:clamp(18px,3vh,30px);border:2px solid #cbd8de;border-radius:24px;background:#fff}.gm12-module-picture img{width:100%;height:100%;object-fit:contain}.gm12-module-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.gm12-module-option{min-height:62px;padding:12px 18px;border:2px solid #cbd8de;border-radius:16px;background:#fff;color:#17212b;font:inherit;font-size:clamp(17px,2.2vh,22px);font-weight:700}.gm12-module-option:hover:not(:disabled){border-color:#33a9ca}.gm12-module-option.is-selected{border-color:#79919d;background:#edf2f4}.gm12-module-option.is-correct{border-color:#16875c;background:#dff5e9;color:#126b4a}.gm12-module-option.is-incorrect{border-color:#c63d4b;background:#fde5e8;color:#9d2f3b}.gm12-training>[data-training-feedback].is-correct{color:#167950}.gm12-training>[data-training-feedback].is-wrong{color:#b33443}
    .gm12-training-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.gm12-training-repeat{border-color:#60727d;background:#fff;color:#17212b}.gm12-training-repeat span{color:#17212b}.gm12-intro[hidden],.gm12-training[hidden],.gm12-training-complete[hidden],.gm12-game[hidden]{display:none}@media(max-height:720px){.gm12-module.is-instruction-stage{padding-top:8px}.gm12-intro ol{margin-bottom:7px;font-size:13px;line-height:1.25}.gm12-media-placeholder{height:clamp(100px,18vh,140px);margin-bottom:8px}.gm12-module-picture{width:min(190px,27vh);margin-bottom:10px;padding:12px}.gm12-module-option{min-height:48px;padding:7px}}
  `;container.append(style);return()=>{active=false;accepting=false;token+=1;clearClock();timers.forEach(id=>clearTimeout(id));timers.clear()}
}
