const FIRST_ATTEMPT_SLOT_MS=6000;
export function mount({container,definition,api,close}){
  const trainingWords={"природа и явления":"лес","еда и блюда":"суп","одежда и бытовые приборы":"фен"};
  const trainingWord=trainingWords[definition.selected_stimulus_set]||"лес";
  container.innerHTML=`
    <header class="game-header-new"><div><p class="game-kicker-new mono">РЕЧЬ</p><h2>${definition.title}</h2><p data-instruction>Расположите буквы в правильном порядке.</p></div><div class="game-progress-new" data-progress>Инструкция</div></header>
    <main class="game-stage-new gm14-module is-instruction-stage" data-stage>
      <section class="gm14-intro" data-intro><h3>Как выполнять задание</h3><ol><li>Рассмотрите перемешанные буквы.</li><li>Перетаскивайте буквы в пустые ячейки или выбирайте их последовательными нажатиями.</li><li>Расположите все буквы так, чтобы получилось правильное слово.</li></ol><p class="gm14-example-title">Посмотрите пример</p><div class="gm14-media-placeholder"><span aria-hidden="true">▶</span><strong>Здесь будет GIF с примером</strong><small>Визуальная инструкция будет добавлена позже</small></div><button type="button" class="icon-btn primary-btn" data-start-training><span>Перейти к тренировке</span></button></section>
      <section class="gm14-training" data-training hidden><h3>Тренировочный пример</h3><p>Соберите слово «${trainingWord.toUpperCase()}».</p><div class="gm14-module-play"><div class="gm14-module-slots" data-training-slots></div><div class="gm14-module-bank" data-training-bank></div><p class="gm14-module-hint" data-training-status></p></div></section>
      <section class="game-intro-new gm14-training-complete" data-training-complete hidden><h3>Обучение завершено</h3><p>Вы правильно собрали слово.</p><div class="gm14-training-actions"><button type="button" class="icon-btn gm14-training-repeat" data-repeat-training><span>Повторить тренировку</span></button><button type="button" class="icon-btn primary-btn" data-confirm-start><span>Начать игру</span></button></div></section>
      <section class="gm14-game" data-game hidden><div class="gm14-module-play" data-play><div class="gm14-module-slots" data-slots aria-label="Ячейки для слова"></div><div class="gm14-module-bank" data-bank aria-label="Перемешанные буквы"></div><p class="gm14-module-hint" data-status>Выберите букву, затем свободную ячейку.</p></div><div class="game-result-new" data-result hidden><h3>Игра завершена</h3><p data-result-text></p><button type="button" class="icon-btn primary-btn" data-restart><span>Ещё раз</span></button></div></section>
    </main><footer class="game-actions-new"><button type="button" class="icon-btn" data-close><span>К выбору игр</span></button></footer>`;
  const stage=container.querySelector('[data-stage]'),instruction=container.querySelector('[data-instruction]'),progress=container.querySelector('[data-progress]');
  const intro=container.querySelector('[data-intro]'),training=container.querySelector('[data-training]'),trainingSlots=container.querySelector('[data-training-slots]'),trainingBank=container.querySelector('[data-training-bank]'),trainingStatus=container.querySelector('[data-training-status]'),trainingComplete=container.querySelector('[data-training-complete]');
  const game=container.querySelector('[data-game]'),play=container.querySelector('[data-play]'),slots=container.querySelector('[data-slots]'),bank=container.querySelector('[data-bank]'),status=container.querySelector('[data-status]'),result=container.querySelector('[data-result]'),resultText=container.querySelector('[data-result-text]'),restart=container.querySelector('[data-restart]');
  let state=null,selectedTile=null,placements=[],submitting=false,firstAttempt=true,shownAt=0,active=true,token=0,trainingSelected=null;const timers=new Set();
  const delay=milliseconds=>new Promise(resolve=>{const id=setTimeout(()=>{timers.delete(id);resolve()},milliseconds);timers.add(id)});const showOnly=target=>[intro,training,trainingComplete,game].forEach(section=>{section.hidden=section!==target});
  function trainingMove(tile,destination){if(!tile||!destination||tile.parentElement===destination)return;const source=tile.parentElement,occupant=destination.classList.contains('gm14-module-slot')?destination.querySelector('.gm14-module-tile'):null;if(occupant&&occupant!==tile){source.classList.contains('gm14-module-slot')?source.append(occupant):trainingBank.append(occupant)}destination.append(tile);trainingSelected?.classList.remove('is-selected');trainingSelected=null;checkTrainingWord()}
  function trainingZone(zone){zone.ondragover=event=>event.preventDefault();zone.ondrop=event=>{event.preventDefault();trainingMove(container.querySelector(`[data-training-tile="${CSS.escape(event.dataTransfer.getData('text/plain'))}"]`),zone)};zone.onclick=event=>{if(event.target===zone&&trainingSelected)trainingMove(trainingSelected,zone)}}
  function trainingTile(letter,id){const tile=document.createElement('button');tile.type='button';tile.className='gm14-module-tile';tile.textContent=letter;tile.draggable=true;tile.dataset.trainingTile=id;tile.dataset.letter=letter.toLowerCase();tile.ondragstart=event=>event.dataTransfer.setData('text/plain',id);tile.onclick=event=>{event.stopPropagation();if(tile.parentElement.classList.contains('gm14-module-slot'))trainingMove(tile,trainingBank);else{trainingSelected?.classList.remove('is-selected');trainingSelected=trainingSelected===tile?null:tile;trainingSelected?.classList.add('is-selected')}};return tile}
  function beginTraining(){token+=1;stage.classList.remove('is-instruction-stage');showOnly(training);progress.textContent='Тренировка';instruction.textContent=`Переставьте буквы и соберите слово «${trainingWord.toUpperCase()}».`;trainingStatus.textContent='Выберите букву, затем пустую ячейку.';trainingSlots.classList.remove('is-error');trainingSlots.replaceChildren();trainingBank.replaceChildren();trainingSelected=null;for(let index=0;index<trainingWord.length;index+=1){const slot=document.createElement('div');slot.className='gm14-module-slot';trainingZone(slot);trainingSlots.append(slot)}trainingZone(trainingBank);[...trainingWord].reverse().forEach((letter,index)=>trainingBank.append(trainingTile(letter.toUpperCase(),`training-${index}`)))}
  function checkTrainingWord(){const tiles=[...trainingSlots.children].map(slot=>slot.querySelector('.gm14-module-tile'));if(tiles.some(tile=>!tile))return;const word=tiles.map(tile=>tile.dataset.letter).join('');if(word!==trainingWord){trainingStatus.textContent='Пока неверно. Переставьте буквы.';trainingSlots.classList.add('is-error');setTimeout(()=>trainingSlots.classList.remove('is-error'),350);return}trainingStatus.textContent='Верно.';const currentToken=token;setTimeout(()=>{if(!active||currentToken!==token)return;showOnly(trainingComplete);progress.textContent='Обучение завершено';instruction.textContent='Тренировочный пример выполнен правильно.'},450)}

  function locationOf(tile){const parent=tile?.parentElement;return parent?.classList.contains('gm14-module-slot')?`slot-${parent.dataset.slotIndex}`:'bank'}function selectTile(tile){selectedTile?.classList.remove('is-selected');selectedTile=tile;selectedTile?.classList.add('is-selected')}
  function moveTile(tile,destination){if(!tile||!destination||submitting||tile.parentElement===destination)return;const source=tile.parentElement,from=locationOf(tile),occupant=destination.classList.contains('gm14-module-slot')?destination.querySelector('.gm14-module-tile'):null;if(occupant&&occupant!==tile){source?.classList.contains('gm14-module-slot')?source.append(occupant):bank.append(occupant)}destination.append(tile);placements.push({tile_id:tile.dataset.tileId,letter:tile.dataset.letter,from,to:locationOf(tile),timestamp_ms:Date.now()});selectTile(null);maybeSubmit()}
  function bindDropZone(zone){zone.ondragover=event=>event.preventDefault();zone.ondrop=event=>{event.preventDefault();moveTile(container.querySelector(`[data-tile-id="${CSS.escape(event.dataTransfer.getData('text/plain'))}"]`),zone)};zone.onclick=event=>{if(event.target===zone&&selectedTile)moveTile(selectedTile,zone)}}
  function makeTile(item){const tile=document.createElement('button');tile.type='button';tile.className='gm14-module-tile';tile.draggable=true;tile.dataset.tileId=item.id;tile.dataset.letter=item.letter;tile.textContent=item.letter.toUpperCase();tile.ondragstart=event=>{event.dataTransfer.setData('text/plain',item.id);selectTile(tile)};tile.onclick=event=>{event.stopPropagation();tile.parentElement?.classList.contains('gm14-module-slot')?moveTile(tile,bank):selectTile(selectedTile===tile?null:tile)};return tile}
  function renderWord(payload){state=payload;placements=[];submitting=false;firstAttempt=true;shownAt=performance.now();selectTile(null);slots.replaceChildren();bank.replaceChildren();payload.letters.forEach((_,index)=>{const slot=document.createElement('div');slot.className='gm14-module-slot';slot.dataset.slotIndex=String(index);bindDropZone(slot);slots.append(slot)});bindDropZone(bank);payload.letters.forEach(item=>bank.append(makeTile(item)));progress.textContent=`Слово ${payload.word_number} из ${payload.word_count}`;instruction.textContent=payload.correct?'Верно! Соберите следующее слово.':'Расположите буквы в правильном порядке.';status.textContent='Выберите букву, затем свободную ячейку.';result.hidden=true;play.hidden=false}
  async function maybeSubmit(){if(submitting||!state)return;const tiles=[...slots.querySelectorAll('.gm14-module-slot')].map(slot=>slot.querySelector('.gm14-module-tile'));if(tiles.some(tile=>!tile))return;submitting=true;const currentToken=token,assembled=tiles.map(tile=>tile.dataset.letter).join('');if(firstAttempt){status.textContent='Слово составлено, проверяю…';const elapsed=performance.now()-shownAt;if(elapsed<FIRST_ATTEMPT_SLOT_MS)await delay(FIRST_ATTEMPT_SLOT_MS-elapsed)}if(!active||currentToken!==token)return;try{const payload=await api.answer({session_id:state.session_id,assembled,placements,timestamp_ms:Date.now()});if(payload.finished){play.hidden=true;result.hidden=false;restart.disabled=false;progress.textContent='Завершено';instruction.textContent='Все слова собраны.';resultText.textContent=`С первой попытки собрано правильно: ${Math.round(Number(payload.metrics?.u01_first_attempt_word_accuracy||0)*100)}%.`;return}if(payload.correct===false){firstAttempt=false;submitting=false;instruction.textContent='Пока неверно. Переставьте буквы и попробуйте ещё раз.';status.textContent='Нажмите букву в ячейке, чтобы вернуть её вниз.';slots.classList.add('is-error');setTimeout(()=>slots.classList.remove('is-error'),350);return}await delay(350);if(active&&currentToken===token)renderWord(payload)}catch(error){instruction.textContent=`Не удалось проверить слово: ${error.message}`;submitting=false}}
  async function begin(){token+=1;submitting=true;restart.disabled=true;showOnly(game);play.hidden=true;result.hidden=true;instruction.textContent='Подготавливаю слова…';try{renderWord(await api.start())}catch(error){instruction.textContent=`Не удалось начать игру: ${error.message}`;restart.disabled=false}}

  container.querySelector('[data-start-training]').onclick=beginTraining;container.querySelector('[data-repeat-training]').onclick=beginTraining;container.querySelector('[data-confirm-start]').onclick=begin;restart.onclick=begin;container.querySelector('[data-close]').onclick=()=>{active=false;submitting=true;token+=1;timers.forEach(id=>clearTimeout(id));timers.clear();close()};
  const style=document.createElement('style');style.textContent=`
    .gm14-module{display:grid;place-items:center;text-align:center;overflow:hidden}.gm14-module.is-instruction-stage{align-items:start;padding-top:clamp(14px,2.4vh,30px)}.gm14-intro,.gm14-training,.gm14-game{width:min(800px,100%)}.gm14-intro h3,.gm14-training h3{margin:0 0 10px;font-size:clamp(19px,2.3vw,25px)}.gm14-intro ol{width:min(700px,100%);margin:0 auto 16px;padding-left:28px;color:#52606d;text-align:left;font-size:clamp(14px,1.6vw,18px);line-height:1.4}.gm14-intro li+li{margin-top:5px}.gm14-example-title{margin:0 0 7px;font-weight:700}.gm14-media-placeholder{box-sizing:border-box;display:flex;width:min(620px,100%);height:clamp(130px,22vh,230px);margin:0 auto 18px;flex-direction:column;align-items:center;justify-content:center;gap:7px;border:2px dashed #b8cbd5;border-radius:16px;background:#eaf1f4;color:#52606d}.gm14-media-placeholder>span{display:grid;width:46px;height:46px;place-items:center;border-radius:50%;background:#d3e2e9;color:#168ba8}.gm14-media-placeholder strong{color:#263744}.gm14-training>p{color:#52606d}
    .gm14-module-play{display:grid;gap:clamp(22px,5vh,48px);width:min(760px,96%);margin:auto}.gm14-module-play[hidden]{display:none}.gm14-module-slots,.gm14-module-bank{display:flex;flex-wrap:wrap;justify-content:center;gap:clamp(10px,1.8vw,18px)}.gm14-module-bank{min-height:106px;padding:17px;border:2px dashed #b9cbd3;border-radius:22px;background:#edf3f5}.gm14-module-slot,.gm14-module-tile{width:clamp(68px,10vh,92px);aspect-ratio:1;border-radius:18px}.gm14-module-slot{display:grid;place-items:center;border:2px dashed #a8bdc7;background:#fff}.gm14-module-tile{border:2px solid #c4d4da;background:#fff;color:#17212b;font:inherit;font-size:clamp(30px,5vh,46px);font-weight:800;cursor:grab}.gm14-module-tile.is-selected{outline:3px solid #29a9cc;outline-offset:3px}.gm14-module-slots.is-error{animation:gm14-error 300ms ease}.gm14-module-hint{min-height:22px;margin:-25px 0 0;color:#526875}@keyframes gm14-error{25%{transform:translateX(-7px)}75%{transform:translateX(7px)}}
    .gm14-training-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.gm14-training-repeat{border-color:#60727d;background:#fff;color:#17212b}.gm14-training-repeat span{color:#17212b}.gm14-intro[hidden],.gm14-training[hidden],.gm14-training-complete[hidden],.gm14-game[hidden]{display:none}@media(max-height:700px){.gm14-module.is-instruction-stage{padding-top:8px}.gm14-intro ol{margin-bottom:7px;font-size:13px;line-height:1.25}.gm14-media-placeholder{height:clamp(100px,18vh,140px);margin-bottom:8px}.gm14-module-play{gap:25px}.gm14-module-bank{min-height:82px;padding:10px}.gm14-module-slot,.gm14-module-tile{width:clamp(58px,9vh,76px)}}
  `;container.append(style);return()=>{active=false;submitting=true;token+=1;timers.forEach(id=>clearTimeout(id));timers.clear()}
}
