export function mount({ container, definition, api, close }) {
  container.innerHTML = `<header class="game-header-new"><div><p class="game-kicker-new mono">ПАМЯТЬ</p><h2>${definition.title}</h2><p>Запомните предметы и восстановите их расположение.</p></div></header><main class="game-stage-new gm03"><p data-info></p><div data-grid class="gm03-grid"></div><p data-timer></p></main><footer class="game-actions-new"><button type="button" data-close class="icon-btn"><span>К выбору игр</span></button></footer>`;
  const grid=container.querySelector("[data-grid]"),info=container.querySelector("[data-info]"),timer=container.querySelector("[data-timer]"); let active=true;
  const files={"Чайник":"kettle.png","Чашка":"cup.png","Яблоко":"apple.png","Ложка":"spoon.png","Хлеб":"bread.png","Мыло":"soap.png","Щётка":"toothbrush.png","Полотенце":"towel.png","Расчёска":"comb.png","Губка":"sponge.png","Лампа":"lamp.png","Книга":"book.png","Часы":"clock.png","Цветок":"flower.png","Телефон":"phone.png"};
  const visual=name=>`<img class="gm03-image" src="/game-assets/objects/${files[name]}" alt=""><small>${name}</small>`;
  const cells=()=>Array.from({length:16},(_,i)=>{const b=document.createElement("button");b.type="button";b.className="gm03-cell";b.dataset.cell=i;return b;});
  async function render(p){if(!active)return; grid.replaceChildren(...cells()); info.textContent=`${p.room} · сцена ${p.room_number} из ${p.room_count}`; timer.textContent="";
    if(p.phase==="study"){p.objects.forEach(o=>{grid.children[o.cell].innerHTML=visual(o.name);grid.children[o.cell].title=o.name;});let left=p.study_seconds;timer.textContent=`Запоминайте: ${left}`;const id=setInterval(async()=>{if(!active){clearInterval(id);return;}left--;timer.textContent=`Запоминайте: ${left}`;if(left<=0){clearInterval(id);render(await api.answer({session_id:p.session_id,action:"begin_recall"}));}},1000);return;}
    info.textContent=`Где находился предмет «${p.target.name}»?`; [...grid.children].forEach((b,i)=>b.onclick=async()=>{[...grid.children].forEach(x=>x.disabled=true);const n=await api.answer({session_id:p.session_id,selected_cell:i});if(n.finished){grid.replaceChildren();info.textContent=`Завершено. Правильных ответов: ${Math.round(n.metrics.u01_correct_action_rate*100)}%`;return;}setTimeout(()=>render(n),350);});
  }
  container.querySelector("[data-close]").onclick=close;const style=document.createElement("style");style.textContent=`.gm03{max-width:760px;margin:auto;text-align:center}.gm03-grid{display:grid;grid-template-columns:repeat(4,120px);gap:14px;justify-content:center;margin:24px}.gm03-cell{height:120px;border:1px solid #b8c8d1;border-radius:16px;background:#fff;color:#17212b;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px}.gm03-cell small{font-size:12px}.gm03-image{width:78px;height:78px;object-fit:contain}`;container.append(style);api.start().then(render);return()=>{active=false};
}
